antagonista/antagonista/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('web.urls')),
    url('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

antagonista/web/urls.py
from django.conf.urls import url

from . import views
#app

app_name = 'web'

urlpatterns = [

    url(r'^$', views.index_video, name='index_video'),
    url(r'^inicio$', views.inicio, name='inicio'),
    url(r'^obras/$', views.obras, name='obras'),
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^escuela/$', views.escuela, name='escuela'),
    url(r'^compania/$', views.compania, name='compania'),
    url(r'^yo_tambien/$', views.yotambien, name='yotambien'),
    url(r'^coloquios/$', views.coloquios, name='coloquios'),
    url(r'^malentendido/$', views.malentendido, name='malentendido'),
    url(r'^silencio/$', views.silencio, name='silencio'),
    url(r'^lagaviota/$', views.lagaviota, name='lagaviota'),
    url(r'^direcciones/$', views.direcciones, name='direcciones'),
    url(r'^brujas/$', views.brujas, name='brujas'),
    url(r'^bellcross/$', views.bellcross, name='bellcross')


]

antagonista/web/models.py
from django.db import models

# Create your models here.

antagonista/web/views.py
from django.shortcuts import render

# Create your views here.


def index_video(request):
    context = {}
    return render(request, 'index.html', context)


def inicio(request):
    context = {'message': 'hola'}
    return render(request, 'inicio.html', context)


def contacto(request):
    context = {}
    print('Estoy en contacto')
    return render(request, 'contacto.html', context)

def obras(request):
    context = {}
    return render(request, 'obras.html', context)

def escuela(request):
    context = {}
    return render(request, 'escuela.html', context)

def yotambien(request):
    context = {}
    return render(request, 'yo_tambien.html', context)

def coloquios(request):
    context = {}
    return render(request, 'coloquios.html', context)

def malentendido(request):
    context = {}
    return render(request, 'elmalentendido.html', context)

def brujas(request):
    context = {}
    return render(request, 'lasbrujas.html', context)

def silencio(request):
    context = {}
    return render(request, 'silencio.html', context)

def direcciones(request):
    context = {}
    return render(request, 'direcciones.html', context)

def lagaviota(request):
    context = {}
    return render(request, 'lagaviota.html', context)

def compania(request):
    context = {}
    return render(request, 'compania.html', context)

def bellcross(request):
    context = {}
    return render(request, 'bellcross.html', context)

antagonista/templates/index-antagonista.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <!-- META -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="...">
    <meta name="keywords" content="...">

    <!-- FACEBOK & TWITTER INTEGRACION -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- TITLE -->
    <title>
        Antagonista
    </title>

    <!-- FAVICONS -->
    <link rel="shortcut icon" href="{% static '/images/favicon.png' %}">

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

    <!-- FONT AWESOME -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'app-assets/fonts/font-awesome/css/font-awesome.min.css' %}"> -->

    <!-- TOASTER -->
    <!-- <link href="{% static 'assets2/css/toastr/toastr.css' %}" rel="stylesheet"> -->

    <!-- DEFAULT CSS -->
    <link rel="stylesheet" href="{% static '/static/css/default.css' %}">
    <link rel="stylesheet" href="{% static '/static/css/layout.css' %}">
    <link rel="stylesheet" href="{% static '/static/css/media-queries.css' %}">
    <link rel="stylesheet" href="{% static '/static/css/fondo.css' %}">

    <!-- BOOTSTRAP  -->


    {% block style %}
    {% endblock %}

</head>

<body>

    <div class="app-content content container">
        <!-- migas de pan -->
        <div class="content-wrapper">
            <div class="content-body">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- DEAFULT VENDORS -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.10.2.min.js"><\/script>')</script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

    <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    <script src="{% static 'js/gmaps.js' %}"></script>
    <script src="{% static 'js/waypoints.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.js' %}"></script>
    <script src="{% static 'js/jquery.placeholder.js' %}"></script>
    <script src="{% static 'js/backstretch.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
    <!-- BOOSTRAP -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block script %}
    {% endblock %}

</body>

</html>

antagonista/templates/partials/breadcrumbs.html
<div class="section-breadcrumb">
  <!-- begin: breadcrumb -->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      {{title}}
    </li>
    <li class="breadcrumb-item">
      <a href={{ href }}>{{subtitle}}</a>
    </li>
    {% for item in name %}
    <li class="breadcrumb-item active">
      <strong>{{item}}</strong>
    </li>
    {% endfor %}
  </ol>
  <!-- end: breadcrumb -->
</div>

antagonista/templates/partials/burger-menu.html
<nav id="colorlib-main-nav" role="navigation">
	<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
	<div class="js-fullheight colorlib-table">
		<div class="colorlib-table-cell js-fullheight">
			<ul>
				<li><a href="{% url 'web:inicio' %}" style="height: 120px">INICIO</a></li>
				<li><a href="{% url 'web:obras' %}" style="height: 120px">OBRAS</a></li>
                <li>
                    <a href="{% url 'web:escuela' %}" style="height: 120px">ESCUELA</a>
                </li>
				<li><a href="about.html"   style="height: 120px">COMPAÑIA</a></li>
				<li><a href="{% url 'web:contacto' %}" style="height: 120px">CONTACTO</a></li>
			</ul>
		</div>
	</div>
</nav>

antagonista/web/templates/agenda.html
{% extends 'index-app.html' %}
{% load static %}
{% block content %}

<nav id="colorlib-main-nav" role="navigation">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
    <div class="js-fullheight colorlib-table">
        <div class="colorlib-table-cell js-fullheight">
            <ul>
                <li><a href="{% url 'web:inicio' %}" style="height: 120px">INICIO</a></li>
                <li><a href="{% url 'web:obras' %}" style="height: 120px">OBRAS</a></li>
                <li>
                    <a href="{% url 'web:escuela' %}" style="height: 120px">ESCUELA</a>
                </li>
                <li><a href="{% url 'web:compania' %}"   style="height: 120px">COMPAÑIA</a></li>
                <li><a href="{% url 'web:contacto' %}" style="height: 120px">CONTACTO</a></li>
            </ul>
        </div>
    </div>
</nav>
<div id="colorlib-page">
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="colorlib-navbar-brand">
                        <a href="{% url 'web:inicio' %}"> <img src="{% static 'images/logo.png' %}" alt="Antagonista" style="height:100px; width:166px;"> </a>
                    </div>
                    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
                </div>
            </div>
        </div>
    </header>

    <aside id="colorlib-hero">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url('/static/images/cover_img_5.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            </ul>
        </div>
    </aside>

    <section class="containerobra" style="padding: 19px 13px 12px 34px;">
        <ul class="list" style="margin-bottom: 100px;">

            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:lagaviota' %}"><span>La Gaviota / Antón Chejov</span> <sup>2017</sup>
                   </a>
               </h3>
            </li>
            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:brujas' %}"><span>Las Brujas de Salem / Arthur Miller</span> <sup>2017</sup>
                   </a>
               </h3>
            </li>

        </ul>
    </section>
</div>


<style>

    .section-title {
        font-size: 2em;
        line-height: 1.16667em;
        margin-bottom: .66667em;
        text-transform: uppercase;
        font-family: HelveticaProBlack,Helvetica,Impact,Arial,sans-serif;
    }

    .item, .item a {
        position: relative;
    }

    .item {
        display: inline-block;
        vertical-align: top;
        width: 100%;
        overflow-x: hidden;
        margin-bottom: 2.66667em;
    }

    .item a {
        display: block;
        opacity: 1;
        -webkit-transition: opacity .2s linear .1s;
        transition: opacity .2s linear .1s;
    }

    .item, .item a {
        position: relative;
    }

    a, a:active, a:hover, a:visited {
        color: inherit;
    }
    a {
        text-decoration: none;
    }

    a:focus, a:hover, button:focus, input:focus, select:focus, textarea:focus {
        outline: none;
        text-decoration: inherit !important;

    }

    .item-prod a:after {
        content: "";
        display: block;
        background: #242d27;
        height: 2px;
        width: 10em;
        margin-top: 1em;
    }

    *, :after, :before, html, input[type=search] {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    .item a:focus, a:hover, .mdzr-no-touchevents .item a:hover {
        opacity: .5;
        text-decoration: inherit !important;
    }

    .item-prod .title {
        text-transform: uppercase;
    }

    .title {
        font-size: 2em;
        line-height: 1em;
    }

    .big-title, .cta, .dancer-nav span, .filters a, .filters button, .filters u, .hero text, .section-title, .super-title, .text h4, .text h5, .title {
        font-weight: 700;
        font-family: HelveticaProBlack,Helvetica,Impact,Arial,sans-serif !important;
        font-kerning: auto;
        font-variant-ligatures: discretionary-ligatures,contextual;
        font-variant-numeric: diagonal-fractions;
        font-feature-settings: "case","dlig","frac","kern","liga","ordn","ornm";
    }

    .item-prod .datetime, .item-prod p {
        display: block;
        font-weight: 700;
        font-size: 0.9em;
        line-height: 1.11111em;
        padding-bottom: .44444em;
    }

    p, ul {
        margin: 0;
    }

    body {
        font-family: Courier,monospace !important;
        font-weight: 400 !important;
        font-style: normal !important;
        line-height: inherit !important;
    }

    h1, h2, h3, h4, h5, h6 {
        color: rgba(0, 0, 0, 0.8);
        font-family: "Inconsolata", monospace;
        font-weight: 400;
        margin: 0 0 0 0;
    }
    p{

       font-family: Courier,monospace !important;

    }
    .title {
        font-size: 1em;
        line-height: 1em;
    }

    .section-title {
        font-size: 2em;
        line-height: 1.16667em;
        margin-bottom: .66667em;
        text-transform: uppercase;
    }

    h1, h2, h3, h4, h5, h6 {
        margin: 0;
        font-weight: 400;
        font-size: 1em;
    }
    .container {
        padding: 0 2.66667em;
    }

    .container {
        position: relative;
        width: 100%;
        <!--max-width: 1280px;-->
        padding: 0 1.33333em;
        clear: both;
        margin-right: 0;
        margin-left: 0;
    }

    .home-container {
        position: relative;
    }


    .section-title {
        font-size: 20px;
        margin-left: 40px;
    }

    .cta {
    text-transform: uppercase;
        display: inline-block;
        font-size: 2em;
        line-height: 1.16667em;
        padding-bottom: 2px;
        border-bottom: 2px solid #242d27;
    }

        @media (min-width: 48em)
    .containerobra {
        padding: 0 2.66667em;
    }

    .containerobra {
        position: relative;
        width: 100%;
        max-width: 1885px;
        padding: 0 1.33333em;
        clear: both;
    }
    .list li {
        margin-bottom: 1.33333em;
        text-transform: uppercase;
    }
    .big-title, .cta, .dancer-nav span, .filters a, .filters button, .filters u, .hero text, .section-title, .super-title, .text h4, .text h5, .title {
        font-weight: 400;
        font-family: Impact;

    }
    .big-title span {
        padding-right: .16667em;
        font-size: 1.9em;
        line-height: 1.14286em;
        font-family: Impact;
        color :  #242d27

    }

    .big-title sup {
        font-family: Courier,monospace;
        <!--font-size: 1.16667em;-->
        line-height: 1.14286em;
        vertical-align: top;
        top: auto;
    }
    p, ul {
        margin: 0;
    }

    ul {
        list-style: none;
        padding: 0;
    }
    h3{
        margin: 0;
        font-weight: 100;
        font-size: 1em;
    }
    .list a {
        opacity: 1;
        transition: opacity .2s linear;
    }
    a, a:active, a:hover, a:visited {
        color: inherit;
    }
    a {
        text-decoration: none;
    }
    a:hover, a.span:hover   {color: gray;    text-decoration: none;}
</style>

{% endblock %}

{% block script %}
{% endblock %}

antagonista/web/templates/index.html
{% extends 'index-antagonista.html' %}
{% load static %}
{% block content %}
<section>
    <video autoplay muted loop id="myVideo">
      <source src="{% static 'images/final.mp4' %}" type="video/mp4">
    </video>

    <div class="content">
      <a href="{% url 'web:inicio' %}" >
        <img src="{% static 'images/logo.png' %}" alt="Antagonista">
      </a>
    </div>
</section>

<style>
* {
    box-sizing: border-box;
}


#myVideo {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%; 
    min-height: 100%;
}

.content {
    position: fixed;
    bottom: 0;
    color: #f1f1f1;
    width: 100%;
    padding: 20px;
    left: 0px;
}

img, video, iframe, embed, object {
    max-width: 23% !important;
    display: block;
    margin: auto;
    padding: 0px !important;
}


</style>


{% endblock %}

{% block script %}
<script>
var video = document.getElementById("myVideo");
var btn = document.getElementById("myBtn");

function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>
{% endblock %}

antagonista/web/templates/obras.html
{% extends 'index-app.html' %}
{% load static %}
{% block content %}

<nav id="colorlib-main-nav" role="navigation">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
    <div class="js-fullheight colorlib-table">
        <div class="colorlib-table-cell js-fullheight">
            <ul>
                <li><a href="{% url 'web:inicio' %}" style="height: 120px">INICIO</a></li>
                <li><a href="{% url 'web:obras' %}" style="height: 120px">OBRAS</a></li>
                <li>
                    <a href="{% url 'web:escuela' %}" style="height: 120px">ESCUELA</a>
                </li>
                <li><a href="{% url 'web:compania' %}"   style="height: 120px">COMPAÑIA</a></li>
                <li><a href="{% url 'web:contacto' %}" style="height: 120px">CONTACTO</a></li>
            </ul>
        </div>
    </div>
</nav>
<div id="colorlib-page">
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="colorlib-navbar-brand">
                        <a href="{% url 'web:inicio' %}"> <img src="{% static 'images/logo.png' %}" alt="Antagonista" style="height:100px; width:166px;"> </a>
                    </div>
                    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
                </div>
            </div>
        </div>
    </header>

    <aside id="colorlib-hero">
        <div class="flexslider">
            <ul class="slides">
              <li style="background-image: url('/static/images/head_00_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_01_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_02_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_03_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_04_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_05_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('/static/images/head_06_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
             <li style="background-image: url('/static/images/head_07_obra.jpg');">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <!-- <h2>Teatro del Antagonista</h2> -->
                                <!-- <h1>ESTRENOS</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            </ul>

        </div>
    </aside>

    <section class="containerobra" style="padding: 19px 13px 12px 34px;">
        <ul class="list" style="margin-bottom: 100px;">

            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:obras' %}"><span>Constelaciones Familiares/ Carla Zuñiga</span> <sup><b>Estreno</b></sup>
                   </a>
               </h3>
            </li>

            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:bellcross' %}"><span>Bell Cross/ Manuel Morgado & Gema Contreras</span> <sup><b>Estreno</b></sup>
                   </a>
               </h3>
            </li>

            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:yotambien' %}"><span>Yo también quiero ser un hombre blanco Heterosexual / Carla Zuñiga</span> <sup>2018</sup>
                   </a>
               </h3>
            </li>
            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:malentendido' %}"><span>El Malentendido / Albert Camus</span> <sup>2016</sup>
                   </a>
               </h3>
            </li>
            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:silencio' %}"><span>Silencio / Aldo Droguett</span> <sup>2012</sup>
                   </a>
               </h3>
            </li>

            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:coloquios' %}"><span>Coloquios / Fernando Cuadra</span> <sup>2011</sup>
                   </a>
               </h3>
            </li>
            <li>
                <h3 class="big-title">
                    <a href="{% url 'web:direcciones' %}"><span>Otras Direcciones</span> <sup>2017</sup>
                   </a>
               </h3>
            </li>
        </ul>
    </section>
</div>


<style>

    #colorlib-hero .flexslider .flex-control-nav li a {
        background: none !important;
    }

    .section-title {
        font-size: 2em;
        line-height: 1.16667em;
        margin-bottom: .66667em;
        text-transform: uppercase;
        font-family: HelveticaProBlack,Helvetica,Impact,Arial,sans-serif;
    }

    .item, .item a {
        position: relative;
    }

    .item {
        display: inline-block;
        vertical-align: top;
        width: 100%;
        overflow-x: hidden;
        margin-bottom: 2.66667em;
    }

    .item a {
        display: block;
        opacity: 1;
        -webkit-transition: opacity .2s linear .1s;
        transition: opacity .2s linear .1s;
    }

    .item, .item a {
        position: relative;
    }

    a, a:active, a:hover, a:visited {
        color: inherit;
    }
    a {
        text-decoration: none;
    }

    a:focus, a:hover, button:focus, input:focus, select:focus, textarea:focus {
        outline: none;
        text-decoration: inherit !important;

    }

    .item-prod a:after {
        content: "";
        display: block;
        background: #242d27;
        height: 2px;
        width: 10em;
        margin-top: 1em;
    }

    *, :after, :before, html, input[type=search] {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    .item a:focus, a:hover, .mdzr-no-touchevents .item a:hover {
        opacity: .5;
        text-decoration: inherit !important;
    }

    .item-prod .title {
        text-transform: uppercase;
    }

    .title {
        font-size: 2em;
        line-height: 1em;
    }

    .big-title, .cta, .dancer-nav span, .filters a, .filters button, .filters u, .hero text, .section-title, .super-title, .text h4, .text h5, .title {
        font-weight: 700;
        font-family: HelveticaProBlack,Helvetica,Impact,Arial,sans-serif !important;
        font-kerning: auto;
        font-variant-ligatures: discretionary-ligatures,contextual;
        font-variant-numeric: diagonal-fractions;
        font-feature-settings: "case","dlig","frac","kern","liga","ordn","ornm";
    }

    .item-prod .datetime, .item-prod p {
        display: block;
        font-weight: 700;
        font-size: 0.9em;
        line-height: 1.11111em;
        padding-bottom: .44444em;
    }

    p, ul {
        margin: 0;
    }

    body {
        font-family: Courier,monospace !important;
        font-weight: 400 !important;
        font-style: normal !important;
        line-height: inherit !important;
    }

    h1, h2, h3, h4, h5, h6 {
        color: rgba(0, 0, 0, 0.8);
        font-family: "Inconsolata", monospace;
        font-weight: 400;
        margin: 0 0 0 0;
    }
    p{

       font-family: Courier,monospace !important;

    }
    .title {
        font-size: 1em;
        line-height: 1em;
    }

    .section-title {
        font-size: 2em;
        line-height: 1.16667em;
        margin-bottom: .66667em;
        text-transform: uppercase;
    }

    h1, h2, h3, h4, h5, h6 {
        margin: 0;
        font-weight: 400;
        font-size: 1em;
    }
    .container {
        padding: 0 2.66667em;
    }

    .container {
        position: relative;
        width: 100%;
        <!--max-width: 1280px;-->
        padding: 0 1.33333em;
        clear: both;
        margin-right: 0;
        margin-left: 0;
    }

    .home-container {
        position: relative;
    }


    .section-title {
        font-size: 20px;
        margin-left: 40px;
    }

    .cta {
    text-transform: uppercase;
        display: inline-block;
        font-size: 2em;
        line-height: 1.16667em;
        padding-bottom: 2px;
        border-bottom: 2px solid #242d27;
    }

        @media (min-width: 48em)
    .containerobra {
        padding: 0 2.66667em;
    }

    .containerobra {
        position: relative;
        width: 100%;
        max-width: 1885px;
        padding: 0 1.33333em;
        clear: both;
    }
    .list li {
        margin-bottom: 1.33333em;
        text-transform: uppercase;
    }
    .big-title, .cta, .dancer-nav span, .filters a, .filters button, .filters u, .hero text, .section-title, .super-title, .text h4, .text h5, .title {
        font-weight: 400;
        font-family: Impact;

    }
    .big-title span {
        padding-right: .16667em;
        font-size: 1.9em;
        line-height: 1.14286em;
        font-family: Impact;
        color :  #000000

    }

    .big-title sup {
        font-family: Courier,monospace;
        <!--font-size: 1.16667em;-->
        line-height: 1.14286em;
        vertical-align: top;
        top: auto;
    }
    p, ul {
        margin: 0;
    }

    ul {
        list-style: none;
        padding: 0;
    }
    h3{
        margin: 0;
        font-weight: 100;
        font-size: 1em;
    }
    .list a {
        opacity: 1;
        transition: opacity .2s linear;
    }
    a, a:active, a:hover, a:visited {
        color: inherit;
    }
    a {
        text-decoration: none;
    }
    a:hover, a.span:hover   {color: gray;    text-decoration: none;}
</style>

{% endblock %}

{% block script %}
{% endblock %}